### ISSUE TITLE
LastAntibodyTest in Recipients missing

### ISSUE THREAD

**Issue by jingmeb** [jingmeb/scandat3#2]
Kolumnen "LastAntibodyTest" i recipients (mottagare) har missing value för alla rader i:
- RJH
- VLL 

Båda dessa har icke-java baserade Prosang - kanske fel begränsat till dessa?

Finns för Uppsala, där det kan stå "NOT_PERFORMED".

**Comment by gustafedgren** [comment]
skulle tro det. Ignorera.
